### PR TITLE
feat(logger): add global logger

### PR DESCRIPTION
**Pull request by origranot**
Hey, I added a logger module for the project.
The module makes use of the ```@origranot/ts-logger``` library to provide a logging service. The logging service can be injected into other modules and components using the ```LOGGER_INJECTION_KEY```.

To use the logging service, first, it needs to be imported and then injected into the component or module using the @Inject decorator.

Here is an example of how to use the Logger service:
```typescript
import { Injectable, Inject } from '@nestjs/common';
import { LOGGER_INJECTION_KEY } from './app-logger.module';
import { Logger } from '@origranot/ts-logger';

@Injectable()
export class MyService {
  constructor(
    @Inject(LOGGER_INJECTION_KEY) private logger: Logger,
  ) {}

  doSomething() {
    this.logger.debug('doing something');
    // ...
  }
}
```

This implementation of the logger module makes it easy to log messages throughout the project. By using the LOGGER_INJECTION_KEY, it ensures that the same instance of the logger is used throughout the project, which helps to maintain consistency in logging.

### CODE REVIEW

**Review by AmitGit217 — CHANGES_REQUESTED** [review]
I'm sorry but this feature already has been implemented globally with very descriptive logs. You can feel free to go the the `mathmate-server/src/dev/all-exceptions.filter.ts` there is a class for that.
 If you want to improve the solution in any way please add to the existing solution and don't duplicate the feature. 
 
 Thank you :)

**Comment by origranot** [comment]
I can see that you created a filter to implement some kind of logger middleware for exceptions.
This is the minimal usage of a logger, what if you want to log an info message? or want to use the logger somewhere else?

**Comment by AmitGit217** [comment]
@origranot  What do you mean by 'info message'?

**Comment by origranot** [comment]
> @origranot What do you mean by 'info message'?

You might want to log information for debug and etc..

**Comment by AmitGit217** [comment]
@origranot I would like to see a screen shot for comparison between our current logs (we have api.logs and errors logs) and the new one you suggested.

**Comment by origranot** [comment]
> @origranot I would like to see a screen shot for comparison between our current logs (we have api.logs and errors logs) and the new one you suggested.

What do you mean by screenshot?
In your implementation you can't use the logger somewhere else.

**Comment by AmitGit217** [comment]
@origranot So to where your logs are sent?
We do want to save our logs somewhere...

**Comment by origranot** [comment]
> @origranot So to where your logs are sent? We do want to save our logs somewhere...

You can choose what you want to do with the logs.
This library supports Console, File and UDP server (Splunk / ELK / other log storage) as a transports.

**Pull request merged**
